const familyData = [
  //   { id:"p1", name:"יוסף (1918–1999)", gender:"M", birth:1918, death:1999, photo:"https://picsum.photos/seed/y1/300/300", bio:"עלה מפולין, נגר אומן ואב למשפחה גדולה.", spouse:"p2", parents:[], children:["p3","p4"] },
  //   { id:"p2", name:"שרה (1922–2005)", gender:"F", birth:1922, death:2005, photo:"https://picsum.photos/seed/s1/300/300", bio:"מורה לספרות, אהבה צילום וטיולים.", spouse:"p1", parents:[], children:["p3","p4"] },

  //   { id:"p3", name:"דוד (1948–)", gender:"M", birth:1948, photo:"https://picsum.photos/seed/d1/300/300", bio:"מהנדס חשמל, מנגן בחליל צד.", spouse:"p5", parents:["p1","p2"], children:["p6","p7","p8"] },
  //   { id:"p4", name:"נעמי (1952–)", gender:"F", birth:1952, photo:"https://picsum.photos/seed/n1/300/300", bio:"ספרנית, אוספת דגמי מיניאטורות.", spouse:"p9", parents:["p1","p2"], children:["p10"] },

  //   { id:"p5", name:"רחל (1951–)", gender:"F", birth:1951, photo:"https://picsum.photos/seed/r1/300/300", bio:"אדריכלית נוף, אוהבת גינון.", spouse:"p3", parents:[], children:["p6","p7","p8"] },
  //   { id:"p9", name:"אורי (1950–)", gender:"M", birth:1950, photo:"https://picsum.photos/seed/u1/300/300", bio:"מורה למתמטיקה וחובב שחמט.", spouse:"p4", parents:[], children:["p10"] },

  //   { id:"p6", name:"יעל (1976–)", gender:"F", birth:1976, photo:"https://picsum.photos/seed/y2/300/300", bio:"מאמנת כושר ורצה מרתונים. גדשג דשג דשג שדג דגשד גדש גשד גדשג שדג שדג שדג שדג שדג דשג שדג שדג שד גשדג שדג שדג שדג שדג שדגדגדגדג דג דג דג דג דג דשגש ד גדגש דגגשדגדגדשגדשג שדג שדג שדג שג", spouse:"p11", parents:["p3","p5"], children:["p12","p13"] },
  //   { id:"p7", name:"איתן (1979–)", gender:"M", birth:1979, photo:"https://picsum.photos/seed/e1/300/300", bio:"מפתח תוכנה, מנגן בבס.", spouse:"p14", parents:["p3","p5"], children:["p15"] },
  //   { id:"p8", name:"מאיה (1984–)", gender:"F", birth:1984, photo:"https://picsum.photos/seed/m1/300/300", bio:"רופאה ילדים, חובבת צילום.", spouse:null, parents:["p3","p5"], children:[] },
  //   { id:"p10", name:"תמר (1978–)", gender:"F", birth:1978, photo:"https://picsum.photos/seed/t1/300/300", bio:"מעצבת פנים.", spouse:"p16", parents:["p4","p9"], children:["p17","p18"] },

  //   { id:"p11", name:"גלעד (1975–)", gender:"M", birth:1975, photo:"https://picsum.photos/seed/g1/300/300", bio:"יזם חברתי.", spouse:"p6", parents:[], children:["p12","p13"] },
  //   { id:"p14", name:"קרן (1981–)", gender:"F", birth:1981, photo:"https://picsum.photos/seed/k1/300/300", bio:"יועצת קריירה.", spouse:"p7", parents:[], children:["p15"] },
  //   { id:"p16", name:"יוני (1977–)", gender:"M", birth:1977, photo:"https://picsum.photos/seed/y3/300/300", bio:"מתכנת ומוזיקאי.", spouse:"p10", parents:[], children:["p17","p18"] },

  //   { id:"p12", name:"ליאן (2005–)", gender:"F", birth:2005, photo:"https://picsum.photos/seed/l1/300/300", bio:"סטודנטית לביולוגיה.", parents:["p6","p11"], spouse:null, children:[] },
  //   { id:"p13", name:"אור (2009–)", gender:"M", birth:2009, photo:"https://picsum.photos/seed/o1/300/300", bio:"שחקן כדורסל נלהב.", parents:["p6","p11"], spouse:null, children:[] },
  //   { id:"p15", name:"נועם (2012–)", gender:"M", birth:2012, photo:"https://picsum.photos/seed/n2/300/300", bio:"אוהב רובוטיקה.", parents:["p7","p14"], spouse:null, children:[] },
  //   { id:"p17", name:"אלה (2010–)", gender:"F", birth:2010, photo:"https://picsum.photos/seed/e2/300/300", bio:"מציירת קומיקס.", parents:["p10","p16"], spouse:null, children:[] },
  //   { id:"p18", name:"עידו (2014–)", gender:"M", birth:2014, photo:"https://picsum.photos/seed/i1/300/300", bio:"בונה בלגו כמו מקצוען.", parents:["p10","p16"], spouse:null, children:[] },
  {
    id: "p1",
    name: "גלעד מאירסון",
    gender: "M",
    birth: 1994,
    death: null,
    photo: "https://picsum.photos/seed/y1/300/300",
    bio: "עלה מפולין, נגר אומן ואב למשפחה גדולה. עלה מפולין, נגר אומן ואב למשפחה גדולה.",
    spouse: "p2",
    parents: [],
    children: [],
  },
  {
    id: "p2",
    name: "שיר מאירסון",
    gender: "F",
    birth: 1994,
    death: null,
    photo: "https://picsum.photos/seed/y1/300/300",
    bio: "עלה מפולין, נגר אומן ואב למשפחה גדולה. עלה מפולין, נגר אומן ואב למשפחה גדולה.",
    spouse: "p1",
    parents: [],
    children: [],
  },
  {
    id: "p3",
    name: "ארבל (מרים) מאירסון",
    gender: "F",
    birth: 2025,
    death: null,
    photo: "https://picsum.photos/seed/y1/300/300",
    bio: "עלה מפולין, נגר אומן ואב למשפחה גדולה. עלה מפולין, נגר אומן ואב למשפחה גדולה.",
    spouse: null,
    parents: ['p1', 'p2'],
    children: [],
  },
];
